const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

async function main() {
   console.log('🌱 Iniciando seed do banco de dados...')

   // CATEGORIAS
   const categorias = [
      { nome: 'Tecnologia', cor: 'bg-blue-600' },
      { nome: 'Inovação', cor: 'bg-slate-700' },
      { nome: 'Negócios', cor: 'bg-indigo-600' },
      { nome: 'Agro', cor: 'bg-purple-600' },
      { nome: 'IA', cor: 'bg-orange-600' },
   ]

   await prisma.categoria.createMany({
      data: categorias,
      skipDuplicates: true,
   })

   console.log('✅ Categorias criadas')

   // Criar usuário admin
   const hashedPassword = await bcrypt.hash('admin123', 10)
   const admin = await prisma.usuario.create({
      data: {
         nome: 'Administrador',
         email: 'admin@eventos.com',
         senha: hashedPassword,
         tipoUsuario: 'admin',
      },
   })

   console.log('✅ Usuário admin criado')

   // Criar usuário organizador
   const organizador = await prisma.usuario.create({
      data: {
         nome: 'João Organizador',
         email: 'organizador@eventos.com',
         senha: await bcrypt.hash('org123', 10),
         tipoUsuario: 'organizador',
         telefone: '(11) 98765-4321',
      },
   })

   console.log('✅ Usuário organizador criado')

   // Criar mais organizadores
   const maria = await prisma.usuario.create({
      data: {
         nome: 'Maria Silva',
         email: 'maria@eventos.com',
         senha: await bcrypt.hash('maria123', 10),
         tipoUsuario: 'organizador',
         telefone: '(65) 99876-5432',
      },
   })

   const carlos = await prisma.usuario.create({
      data: {
         nome: 'Carlos Santos',
         email: 'carlos@eventos.com',
         senha: await bcrypt.hash('carlos123', 10),
         tipoUsuario: 'organizador',
         telefone: '(65) 98765-1234',
      },
   })

   console.log('✅ Organizadores adicionais criados')

   // Buscar categorias
   const catTecnologia = await prisma.categoria.findFirst({ where: { nome: 'Tecnologia' } })
   const catInovacao = await prisma.categoria.findFirst({ where: { nome: 'Inovação' } })
   const catNegocios = await prisma.categoria.findFirst({ where: { nome: 'Negócios' } })
   const catAgro = await prisma.categoria.findFirst({ where: { nome: 'Agro' } })
   const catIA = await prisma.categoria.findFirst({ where: { nome: 'IA' } })

   // EVENTOS DE EXEMPLO
   const eventos = [
      // DEZEMBRO 2024
      {
         titulo: 'Tech Summit MT 2024',
         descricao:
            'O maior evento de tecnologia e inovação do Mato Grosso. Palestras, workshops e networking com os principais nomes do mercado tech.',
         categoriaId: catTecnologia?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2024-12-15T09:00:00'),
         dataFim: new Date('2024-12-15T18:00:00'),
         capacidadeMaxima: 800,
         vagasDisponiveis: 800,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Eventos do Pantanal',
         LocalEndereco: 'Av. Bernardo Antônio de Oliveira Neto',
         LocalNumero: '500',
         LocalComplemento: 'Centro de Convenções',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-900',
         LocalCapacidade: 800,
         LocalLatitude: -15.601,
         LocalLongitude: -56.0974,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo1',
         linkPaginaEvento: 'https://techsummitmt.com.br',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Workshop IA na Agricultura',
         descricao:
            'Aprenda como a Inteligência Artificial está revolucionando o agronegócio. Cases de sucesso e aplicações práticas.',
         categoriaId: catIA?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2024-12-20T14:00:00'),
         dataFim: new Date('2024-12-20T17:00:00'),
         capacidadeMaxima: 300,
         vagasDisponiveis: 300,
         valorInscricao: 50.0,
         tipoEvento: 'presencial',
         LocalNome: 'Fiemt Senai Várzea Grande',
         LocalEndereco: 'Av. Dom Orlando Chaves',
         LocalNumero: '3000',
         LocalBairro: 'Cristo Rei',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78118-000',
         LocalCapacidade: 300,
         LocalLatitude: -15.6469,
         LocalLongitude: -56.1325,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo2',
         status: 'publicado',
      },
      // JANEIRO 2025 - DIA 10 (VÁRIOS EVENTOS NO MESMO DIA)
      {
         titulo: 'Meetup de Startups - Manhã',
         descricao: 'Networking entre empreendedores e investidores. Pitch de startups e rodadas de negócios.',
         categoriaId: catNegocios?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-01-10T09:00:00'),
         dataFim: new Date('2025-01-10T12:00:00'),
         capacidadeMaxima: 150,
         vagasDisponiveis: 150,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório Sebrae Cuiabá',
         LocalEndereco: 'Av. Historiador Rubens de Mendonça',
         LocalNumero: '4193',
         LocalBairro: 'Bosque da Saúde',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78050-000',
         LocalCapacidade: 350,
         LocalLatitude: -15.5815,
         LocalLongitude: -56.0722,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo3',
         linkPaginaEvento: 'https://sebrae.com.br/eventos',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Workshop de Marketing Digital',
         descricao: 'Estratégias modernas de marketing digital para pequenos e médios negócios.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-01-10T14:00:00'),
         dataFim: new Date('2025-01-10T18:00:00'),
         capacidadeMaxima: 100,
         vagasDisponiveis: 100,
         valorInscricao: 80.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Convenções Senai MT',
         LocalEndereco: 'Av. XV de Novembro',
         LocalNumero: '303',
         LocalBairro: 'Centro',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78110-000',
         LocalCapacidade: 400,
         LocalLatitude: -15.6524,
         LocalLongitude: -56.132,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo4',
         status: 'publicado',
      },
      {
         titulo: 'Palestra: Inovação no Agronegócio',
         descricao: 'Como a tecnologia está transformando o agro em Mato Grosso.',
         categoriaId: catAgro?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-01-10T19:00:00'),
         dataFim: new Date('2025-01-10T21:00:00'),
         capacidadeMaxima: 200,
         vagasDisponiveis: 200,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório da UFMT',
         LocalEndereco: 'Av. Fernando Corrêa da Costa',
         LocalNumero: '2367',
         LocalComplemento: 'Universidade Federal de Mato Grosso',
         LocalBairro: 'Boa Esperança',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78060-900',
         LocalCapacidade: 700,
         LocalLatitude: -15.6047,
         LocalLongitude: -56.0638,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo5',
         status: 'publicado',
      },
      // JANEIRO 2025 - OUTROS EVENTOS
      {
         titulo: 'Webinar: Futuro da IA',
         descricao: 'Evento 100% online sobre as tendências da Inteligência Artificial para 2025.',
         categoriaId: catIA?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-01-25T20:00:00'),
         dataFim: new Date('2025-01-25T22:00:00'),
         capacidadeMaxima: 1000,
         vagasDisponiveis: 1000,
         valorInscricao: 0,
         tipoEvento: 'online',
         linkOnline: 'https://meet.google.com/exemplo',
         LocalNome: 'Online',
         LocalEndereco: 'Plataforma Virtual',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         linkPaginaEvento: 'https://futuroia.com.br',
         status: 'publicado',
      },
      {
         titulo: 'Hackathon Cuiabá 2025',
         descricao: '48 horas de desenvolvimento intenso. Traga sua ideia e monte seu time!',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-01-27T08:00:00'),
         dataFim: new Date('2025-01-29T20:00:00'),
         capacidadeMaxima: 120,
         vagasDisponiveis: 120,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Eventos do Pantanal',
         LocalEndereco: 'Av. Bernardo Antônio de Oliveira Neto',
         LocalNumero: '500',
         LocalComplemento: 'Centro de Convenções',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-900',
         LocalCapacidade: 800,
         LocalLatitude: -15.601,
         LocalLongitude: -56.0974,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo6',
         linkPaginaEvento: 'https://hackathoncuiaba.com.br',
         status: 'publicado',
         destaque: true,
      },
      // FEVEREIRO 2025 - DIA 5 (MÚLTIPLOS EVENTOS)
      {
         titulo: 'Agro Tech Fair - Dia 1',
         descricao: 'Feira de tecnologia para o agronegócio. Exposição de equipamentos e palestras.',
         categoriaId: catAgro?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-02-05T08:00:00'),
         dataFim: new Date('2025-02-05T18:00:00'),
         capacidadeMaxima: 700,
         vagasDisponiveis: 700,
         valorInscricao: 100.0,
         tipoEvento: 'presencial',
         LocalNome: 'Parque de Exposições de Sinop',
         LocalEndereco: 'Av. Alexandre Ferronato',
         LocalNumero: '1500',
         LocalBairro: 'Setor Industrial',
         LocalCidade: 'Sinop',
         LocalEstado: 'MT',
         LocalCep: '78550-000',
         LocalCapacidade: 700,
         LocalLatitude: -11.8576,
         LocalLongitude: -55.5091,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo7',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Curso: Drones na Agricultura',
         descricao: 'Capacitação prática no uso de drones para pulverização e mapeamento agrícola.',
         categoriaId: catAgro?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-02-05T09:00:00'),
         dataFim: new Date('2025-02-05T17:00:00'),
         capacidadeMaxima: 30,
         vagasDisponiveis: 30,
         valorInscricao: 250.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Treinamento Rural Sinop',
         LocalEndereco: 'Rodovia BR-163',
         LocalNumero: 'Km 810',
         LocalBairro: 'Zona Rural',
         LocalCidade: 'Sinop',
         LocalEstado: 'MT',
         LocalCep: '78550-000',
         LocalCapacidade: 50,
         LocalLatitude: -11.87,
         LocalLongitude: -55.52,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo8',
         status: 'publicado',
      },
      {
         titulo: 'Networking Empresarial - Sinop',
         descricao: 'Encontro de empresários do norte de Mato Grosso.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-02-05T19:00:00'),
         dataFim: new Date('2025-02-05T22:00:00'),
         capacidadeMaxima: 150,
         vagasDisponiveis: 150,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro Cultural de Lucas do Rio Verde',
         LocalEndereco: 'Av. Amazonas',
         LocalNumero: '300',
         LocalBairro: 'Centro',
         LocalCidade: 'Lucas do Rio Verde',
         LocalEstado: 'MT',
         LocalCep: '78455-000',
         LocalCapacidade: 500,
         LocalLatitude: -13.0606,
         LocalLongitude: -55.9034,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo9',
         status: 'publicado',
      },
      // FEVEREIRO 2025 - CONTINUAÇÃO
      {
         titulo: 'DevFest Mato Grosso',
         descricao: 'Festival de desenvolvedores com palestras sobre as principais tecnologias do mercado.',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-02-15T08:00:00'),
         dataFim: new Date('2025-02-15T18:00:00'),
         capacidadeMaxima: 500,
         vagasDisponiveis: 500,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Teatro Zulmira Canavarros',
         LocalEndereco: 'Av. André Maggi',
         LocalNumero: '451',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-901',
         LocalCapacidade: 600,
         LocalLatitude: -15.5977,
         LocalLongitude: -56.0978,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo10',
         linkPaginaEvento: 'https://devfestmt.com.br',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Semana da Inovação - Rondonópolis',
         descricao: 'Uma semana inteira dedicada à inovação tecnológica e empreendedorismo.',
         categoriaId: catInovacao?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-02-17T08:00:00'),
         dataFim: new Date('2025-02-21T18:00:00'),
         capacidadeMaxima: 500,
         vagasDisponiveis: 500,
         valorInscricao: 50.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro Cultural de Rondonópolis',
         LocalEndereco: 'Av. Amazonas',
         LocalNumero: '50',
         LocalBairro: 'Centro',
         LocalCidade: 'Rondonópolis',
         LocalEstado: 'MT',
         LocalCep: '78700-000',
         LocalCapacidade: 500,
         LocalLatitude: -16.4673,
         LocalLongitude: -54.6372,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo11',
         status: 'publicado',
      },
      // MARÇO 2025 - DIA 8 (MÚLTIPLOS EVENTOS)
      {
         titulo: 'Encontro de Mulheres na Tecnologia',
         descricao: 'Celebrando o Dia Internacional da Mulher com palestras inspiradoras de mulheres na tech.',
         categoriaId: catTecnologia?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-03-08T09:00:00'),
         dataFim: new Date('2025-03-08T17:00:00'),
         capacidadeMaxima: 300,
         vagasDisponiveis: 300,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório Sebrae Cuiabá',
         LocalEndereco: 'Av. Historiador Rubens de Mendonça',
         LocalNumero: '4193',
         LocalBairro: 'Bosque da Saúde',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78050-000',
         LocalCapacidade: 350,
         LocalLatitude: -15.5815,
         LocalLongitude: -56.0722,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo12',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Workshop: Liderança Feminina',
         descricao: 'Desenvolvimento de habilidades de liderança para mulheres empreendedoras.',
         categoriaId: catNegocios?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-03-08T14:00:00'),
         dataFim: new Date('2025-03-08T18:00:00'),
         capacidadeMaxima: 80,
         vagasDisponiveis: 80,
         valorInscricao: 60.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Convenções Senai MT',
         LocalEndereco: 'Av. XV de Novembro',
         LocalNumero: '303',
         LocalBairro: 'Centro',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78110-000',
         LocalCapacidade: 400,
         LocalLatitude: -15.6524,
         LocalLongitude: -56.132,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo13',
         status: 'publicado',
      },
      {
         titulo: 'Webinar: Empreendedorismo Feminino',
         descricao: 'Evento online sobre desafios e oportunidades para mulheres empreendedoras.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-03-08T19:00:00'),
         dataFim: new Date('2025-03-08T21:00:00'),
         capacidadeMaxima: 800,
         vagasDisponiveis: 800,
         valorInscricao: 0,
         tipoEvento: 'online',
         linkOnline: 'https://meet.google.com/exemplo2',
         LocalNome: 'Online',
         LocalEndereco: 'Plataforma Virtual',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         status: 'publicado',
      },
      // EVENTOS FUTUROS
      {
         titulo: 'Expo Tech Brasil Central',
         descricao: 'A maior exposição de tecnologia da região Centro-Oeste.',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-03-20T08:00:00'),
         dataFim: new Date('2025-03-22T20:00:00'),
         capacidadeMaxima: 2000,
         vagasDisponiveis: 2000,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Parque de Exposições Jonas Pinheiro',
         LocalEndereco: 'Av. Beira Rio',
         LocalNumero: 's/n',
         LocalBairro: 'Dom Aquino',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78015-480',
         LocalCapacidade: 1000,
         LocalLatitude: -15.6162,
         LocalLongitude: -56.0998,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo14',
         linkPaginaEvento: 'https://expotechbc.com.br',
         status: 'publicado',
         destaque: true,
      },
      {
         titulo: 'Curso Avançado de Machine Learning',
         descricao: 'Curso intensivo de 3 dias sobre ML e Deep Learning com certificado.',
         categoriaId: catIA?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-04-10T08:00:00'),
         dataFim: new Date('2025-04-12T18:00:00'),
         capacidadeMaxima: 40,
         vagasDisponiveis: 40,
         valorInscricao: 500.0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório da UFMT',
         LocalEndereco: 'Av. Fernando Corrêa da Costa',
         LocalNumero: '2367',
         LocalComplemento: 'Universidade Federal de Mato Grosso',
         LocalBairro: 'Boa Esperança',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78060-900',
         LocalCapacidade: 700,
         LocalLatitude: -15.6047,
         LocalLongitude: -56.0638,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo15',
         status: 'publicado',
      },
   ]

   for (const evento of eventos) {
      await prisma.evento.create({
         data: evento,
      })
   }

   console.log('✅ Eventos criados')

   console.log('🎉 Seed concluído com sucesso!')
   console.log('📊 Total de eventos criados:', eventos.length)
}

main()
   .catch((e) => {
      console.error('❌ Erro no seed:', e)
      process.exit(1)
   })
   .finally(async () => {
      await prisma.$disconnect()
   })
