const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

async function main() {
   console.log('🌱 Iniciando seed do banco de dados...')

   // CATEGORIAS
   const categorias = [
      { nome: 'Tecnologia', cor: 'bg-blue-600' },
      { nome: 'Inovação', cor: 'bg-slate-700' },
      { nome: 'Negócios', cor: 'bg-indigo-600' },
      { nome: 'Agro', cor: 'bg-purple-600' },
      { nome: 'IA', cor: 'bg-orange-600' },
   ]

   await prisma.categoria.createMany({
      data: categorias,
      skipDuplicates: true,
   })

   console.log('✅ Categorias criadas')

   // Criar usuário admin
   const hashedPassword = await bcrypt.hash('admin123', 10)
   const admin = await prisma.usuario.create({
      data: {
         nome: 'Administrador',
         email: 'admin@eventos.com',
         senha: hashedPassword,
         tipoUsuario: 'admin',
      },
   })

   console.log('✅ Usuário admin criado')

   // Criar usuário organizador
   const organizador = await prisma.usuario.create({
      data: {
         nome: 'João Organizador',
         email: 'organizador@eventos.com',
         senha: await bcrypt.hash('org123', 10),
         tipoUsuario: 'organizador',
         telefone: '(11) 98765-4321',
      },
   })

   console.log('✅ Usuário organizador criado')

   // Criar mais organizadores
   const maria = await prisma.usuario.create({
      data: {
         nome: 'Maria Silva',
         email: 'maria@eventos.com',
         senha: await bcrypt.hash('maria123', 10),
         tipoUsuario: 'organizador',
         telefone: '(65) 99876-5432',
      },
   })

   const carlos = await prisma.usuario.create({
      data: {
         nome: 'Carlos Santos',
         email: 'carlos@eventos.com',
         senha: await bcrypt.hash('carlos123', 10),
         tipoUsuario: 'organizador',
         telefone: '(65) 98765-1234',
      },
   })

   console.log('✅ Organizadores adicionais criados')

   // Buscar categorias
   const catTecnologia = await prisma.categoria.findFirst({ where: { nome: 'Tecnologia' } })
   const catInovacao = await prisma.categoria.findFirst({ where: { nome: 'Inovação' } })
   const catNegocios = await prisma.categoria.findFirst({ where: { nome: 'Negócios' } })
   const catAgro = await prisma.categoria.findFirst({ where: { nome: 'Agro' } })
   const catIA = await prisma.categoria.findFirst({ where: { nome: 'IA' } })

   const eventos = [
      // NOVEMBRO 2025
      {
         titulo: 'Tech Summit MT 2025',
         financiadorTipo: 'privado',
         financiadorNome: 'Federação das Indústrias de Mato Grosso (FIEMT)',
         descricao: 'Maior evento de tecnologia e inovação do Mato Grosso. Palestras, workshops e networking.',
         categoriaId: catTecnologia?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-11-15T09:00:00'),
         dataFim: new Date('2025-11-15T18:00:00'),
         horarioAbertura: new Date('1970-01-01T09:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 800,
         vagasDisponiveis: 800,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Eventos do Pantanal',
         LocalEndereco: 'Av. Bernardo Antônio de Oliveira Neto',
         LocalNumero: '500',
         LocalComplemento: 'Centro de Convenções',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-900',
         LocalCapacidade: 800,
         LocalLatitude: -15.5663648,
         LocalLongitude: -56.1084457,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo1',
         linkPaginaEvento: 'https://techsummitmt.com.br',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Workshop IA na Agricultura',
         financiadorTipo: 'privado',
         financiadorNome: 'SENAI Mato Grosso',
         descricao: 'Aprenda como IA está revolucionando o agronegócio. Cases e aplicações práticas.',
         categoriaId: catIA?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-11-20T14:00:00'),
         dataFim: new Date('2025-11-20T17:00:00'),
         horarioAbertura: new Date('1970-01-01T14:00:00'),
         horarioEncerramento: new Date('1970-01-01T17:00:00'),
         capacidadeMaxima: 300,
         vagasDisponiveis: 300,
         valorInscricao: 50.0,
         tipoEvento: 'presencial',
         LocalNome: 'FIEMT SENAI Várzea Grande',
         LocalEndereco: 'Av. Dom Orlando Chaves',
         LocalNumero: '3000',
         LocalComplemento: '',
         LocalBairro: 'Cristo Rei',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78118-000',
         LocalCapacidade: 300,
         LocalLatitude: -15.6469,
         LocalLongitude: -56.1325,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo2',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // NOVEMBRO 2025 - DIA 10 (VÁRIOS EVENTOS)
      {
         titulo: 'Meetup de Startups - Manhã',
         financiadorTipo: 'privado',
         financiadorNome: 'Serviço Brasileiro de Apoio às Micro e Pequenas Empresas (Sebrae)',
         descricao: 'Networking entre empreendedores e investidores. Pitch de startups.',
         categoriaId: catNegocios?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-11-10T09:00:00'),
         dataFim: new Date('2025-11-10T12:00:00'),
         horarioAbertura: new Date('1970-01-01T09:00:00'),
         horarioEncerramento: new Date('1970-01-01T12:00:00'),
         capacidadeMaxima: 150,
         vagasDisponiveis: 150,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório Sebrae Cuiabá',
         LocalEndereco: 'Av. Historiador Rubens de Mendônça',
         LocalNumero: '4193',
         LocalComplemento: '',
         LocalBairro: 'Bosque da Saúde',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78050-000',
         LocalCapacidade: 350,
         LocalLatitude: -15.5815,
         LocalLongitude: -56.0722,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo3',
         linkPaginaEvento: 'https://sebrae.com.br/eventos',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Workshop de Marketing Digital',
         financiadorTipo: 'privado',
         financiadorNome: 'SENAI Mato Grosso',
         descricao: 'Estratégias de marketing digital para pequenos e médios negócios.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-11-10T14:00:00'),
         dataFim: new Date('2025-11-10T18:00:00'),
         horarioAbertura: new Date('1970-01-01T14:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 100,
         vagasDisponiveis: 100,
         valorInscricao: 80.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Convenções SENAI MT',
         LocalEndereco: 'Av. XV de Novembro',
         LocalNumero: '303',
         LocalComplemento: '',
         LocalBairro: 'Centro',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78110-000',
         LocalCapacidade: 400,
         LocalLatitude: -15.6524,
         LocalLongitude: -56.132,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo4',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Palestra: Inovação no Agronegócio',
         financiadorTipo: 'publico',
         financiadorNome: 'Universidade Federal de Mato Grosso (UFMT)',
         descricao: 'Como a tecnologia está transformando o agro em Mato Grosso.',
         categoriaId: catAgro?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-11-10T19:00:00'),
         dataFim: new Date('2025-11-10T21:00:00'),
         horarioAbertura: new Date('1970-01-01T19:00:00'),
         horarioEncerramento: new Date('1970-01-01T21:00:00'),
         capacidadeMaxima: 200,
         vagasDisponiveis: 200,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório da UFMT',
         LocalEndereco: 'Av. Fernando Corrêa da Costa',
         LocalNumero: '2367',
         LocalComplemento: 'Universidade Federal de Mato Grosso',
         LocalBairro: 'Boa Esperança',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78060-900',
         LocalCapacidade: 700,
         LocalLatitude: -15.6047,
         LocalLongitude: -56.0638,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo5',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // NOVEMBRO 2025 - OUTROS EVENTOS
      {
         titulo: 'Webinar: Futuro da IA',
         financiadorTipo: 'privado',
         financiadorNome: 'Instituto de Tecnologia e Inovação',
         descricao: 'Evento online sobre tendências da Inteligência Artificial para 2025.',
         categoriaId: catIA?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-11-25T20:00:00'),
         dataFim: new Date('2025-11-25T22:00:00'),
         horarioAbertura: new Date('1970-01-01T20:00:00'),
         horarioEncerramento: new Date('1970-01-01T22:00:00'),
         capacidadeMaxima: 1000,
         vagasDisponiveis: 1000,
         valorInscricao: 0,
         tipoEvento: 'online',
         linkOnline: 'https://meet.google.com/exemplo',
         LocalNome: 'Online',
         LocalEndereco: 'Plataforma Virtual',
         LocalNumero: '',
         LocalComplemento: '',
         LocalBairro: '',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '',
         LocalCapacidade: 0,
         LocalLatitude: 0,
         LocalLongitude: 0,
         LocalLinkGoogleMaps: '',
         linkPaginaEvento: 'https://futuroia.com.br',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1581093588401-84b5a3d99f91?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Hackathon Cuiabá 2025',
         financiadorTipo: 'publico',
         financiadorNome: 'Prefeitura Municipal de Cuiabá',
         descricao: 'Desenvolvimento intenso. Traga sua ideia e monte seu time!',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-11-27T08:00:00'),
         dataFim: new Date('2025-11-27T20:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T20:00:00'),
         capacidadeMaxima: 120,
         vagasDisponiveis: 120,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Eventos do Pantanal',
         LocalEndereco: 'Av. Bernardo Antônio de Oliveira Neto',
         LocalNumero: '500',
         LocalComplemento: 'Centro de Convenções',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-900',
         LocalCapacidade: 800,
         LocalLatitude: -15.601,
         LocalLongitude: -56.0974,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo6',
         linkPaginaEvento: 'https://hackathoncuiaba.com.br',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1556157382-97eda2d62296?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // DEZEMBRO 2025 - DIA 5 (MÚLTIPLOS EVENTOS)
      {
         titulo: 'Agro Tech Fair',
         financiadorTipo: 'privado',
         financiadorNome: 'Associação dos Produtores de Soja e Milho de Mato Grosso (Aprosoja)',
         descricao: 'Feira de tecnologia para o agronegócio. Exposição e palestras.',
         categoriaId: catAgro?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-12-05T08:00:00'),
         dataFim: new Date('2025-12-05T18:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 700,
         vagasDisponiveis: 700,
         valorInscricao: 100.0,
         tipoEvento: 'presencial',
         LocalNome: 'Parque de Exposições de Sinop',
         LocalEndereco: 'Av. Alexandre Ferronato',
         LocalNumero: '1500',
         LocalComplemento: '',
         LocalBairro: 'Setor Industrial',
         LocalCidade: 'Sinop',
         LocalEstado: 'MT',
         LocalCep: '78550-000',
         LocalCapacidade: 700,
         LocalLatitude: -11.8576,
         LocalLongitude: -55.5091,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo7',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1496359427652-8c2e5d379be3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Curso: Drones na Agricultura',
         financiadorTipo: 'privado',
         financiadorNome: 'Serviço Nacional de Aprendizagem Rural (Senar)',
         descricao: 'Capacitação no uso de drones para agricultura.',
         categoriaId: catAgro?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-12-05T09:00:00'),
         dataFim: new Date('2025-12-05T17:00:00'),
         horarioAbertura: new Date('1970-01-01T09:00:00'),
         horarioEncerramento: new Date('1970-01-01T17:00:00'),
         capacidadeMaxima: 30,
         vagasDisponiveis: 30,
         valorInscricao: 250.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Treinamento Rural Sinop',
         LocalEndereco: 'Rodovia BR-163',
         LocalNumero: 'Km 810',
         LocalComplemento: 'Zona Rural',
         LocalBairro: '',
         LocalCidade: 'Sinop',
         LocalEstado: 'MT',
         LocalCep: '78550-000',
         LocalCapacidade: 50,
         LocalLatitude: -11.87,
         LocalLongitude: -55.52,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo8',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Networking Empresarial - Sinop',
         financiadorTipo: 'privado',
         financiadorNome: 'Câmara de Dirigentes Lojistas de Sinop',
         descricao: 'Encontro de empresários do norte de Mato Grosso.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-12-05T19:00:00'),
         dataFim: new Date('2025-12-05T22:00:00'),
         horarioAbertura: new Date('1970-01-01T19:00:00'),
         horarioEncerramento: new Date('1970-01-01T22:00:00'),
         capacidadeMaxima: 150,
         vagasDisponiveis: 150,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro Cultural de Lucas do Rio Verde',
         LocalEndereco: 'Av. Amazonas',
         LocalNumero: '300',
         LocalComplemento: '',
         LocalBairro: 'Centro',
         LocalCidade: 'Lucas do Rio Verde',
         LocalEstado: 'MT',
         LocalCep: '78455-000',
         LocalCapacidade: 500,
         LocalLatitude: -13.0606,
         LocalLongitude: -55.9034,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo9',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // DEZEMBRO 2025 - CONTINUAÇÃO
      {
         titulo: 'DevFest Mato Grosso',
         financiadorTipo: 'privado',
         financiadorNome: 'Google Developer Groups (GDG Cuiabá)',
         descricao: 'Festival de desenvolvedores com palestras sobre tecnologias.',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-12-15T08:00:00'),
         dataFim: new Date('2025-12-15T18:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 500,
         vagasDisponiveis: 500,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Teatro Zulmira Canavarros',
         LocalEndereco: 'Av. André Maggi',
         LocalNumero: '451',
         LocalComplemento: '',
         LocalBairro: 'Centro Político Administrativo',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78049-901',
         LocalCapacidade: 600,
         LocalLatitude: -15.5977,
         LocalLongitude: -56.0978,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo10',
         linkPaginaEvento: 'https://devfestmt.com.br',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Semana da Inovação - Rondonópolis',
         financiadorTipo: 'publico',
         financiadorNome: 'Secretaria de Ciência, Tecnologia e Inovação de Mato Grosso (Seciteci)',
         descricao: 'Dedicada à inovação tecnológica e empreendedorismo.',
         categoriaId: catInovacao?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-12-17T08:00:00'),
         dataFim: new Date('2025-12-17T18:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 500,
         vagasDisponiveis: 500,
         valorInscricao: 50.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro Cultural de Rondonópolis',
         LocalEndereco: 'Av. Amazonas',
         LocalNumero: '50',
         LocalComplemento: '',
         LocalBairro: 'Centro',
         LocalCidade: 'Rondonópolis',
         LocalEstado: 'MT',
         LocalCep: '78700-000',
         LocalCapacidade: 500,
         LocalLatitude: -16.4673,
         LocalLongitude: -54.6372,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo11',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // DEZEMBRO 2025 - DIA 8 (MÚLTIPLOS EVENTOS)
      {
         titulo: 'Encontro de Mulheres na Tecnologia',
         financiadorTipo: 'privado',
         financiadorNome: 'WomakersCode',
         descricao: 'Palestras inspiradoras de mulheres na tech.',
         categoriaId: catTecnologia?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-12-08T09:00:00'),
         dataFim: new Date('2025-12-08T17:00:00'),
         horarioAbertura: new Date('1970-01-01T09:00:00'),
         horarioEncerramento: new Date('1970-01-01T17:00:00'),
         capacidadeMaxima: 300,
         vagasDisponiveis: 300,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório Sebrae Cuiabá',
         LocalEndereco: 'Av. Historiador Rubens de Mendônça',
         LocalNumero: '4193',
         LocalComplemento: '',
         LocalBairro: 'Bosque da Saúde',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78050-000',
         LocalCapacidade: 350,
         LocalLatitude: -15.5815,
         LocalLongitude: -56.0722,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo12',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Workshop: Liderança Feminina',
         financiadorTipo: 'privado',
         financiadorNome: 'Sebrae Mato Grosso',
         descricao: 'Desenvolvimento de habilidades de liderança.',
         categoriaId: catNegocios?.id,
         organizadorId: maria.id,
         dataInicio: new Date('2025-12-08T14:00:00'),
         dataFim: new Date('2025-12-08T18:00:00'),
         horarioAbertura: new Date('1970-01-01T14:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 80,
         vagasDisponiveis: 80,
         valorInscricao: 60.0,
         tipoEvento: 'presencial',
         LocalNome: 'Centro de Convenções SENAI MT',
         LocalEndereco: 'Av. XV de Novembro',
         LocalNumero: '303',
         LocalComplemento: '',
         LocalBairro: 'Centro',
         LocalCidade: 'Várzea Grande',
         LocalEstado: 'MT',
         LocalCep: '78110-000',
         LocalCapacidade: 400,
         LocalLatitude: -15.6524,
         LocalLongitude: -56.132,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo13',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Webinar: Empreendedorismo Feminino',
         financiadorTipo: 'privado',
         financiadorNome: 'Sebrae Mato Grosso',
         descricao: 'Desafios e oportunidades para mulheres empreendedoras.',
         categoriaId: catNegocios?.id,
         organizadorId: carlos.id,
         dataInicio: new Date('2025-12-08T19:00:00'),
         dataFim: new Date('2025-12-08T21:00:00'),
         horarioAbertura: new Date('1970-01-01T19:00:00'),
         horarioEncerramento: new Date('1970-01-01T21:00:00'),
         capacidadeMaxima: 800,
         vagasDisponiveis: 800,
         valorInscricao: 0,
         tipoEvento: 'online',
         linkOnline: 'https://meet.google.com/exemplo2',
         LocalNome: 'Online',
         LocalEndereco: 'Plataforma Virtual',
         LocalNumero: '',
         LocalComplemento: '',
         LocalBairro: '',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '',
         LocalCapacidade: 0,
         LocalLatitude: 0,
         LocalLongitude: 0,
         LocalLinkGoogleMaps: '',
         linkPaginaEvento: '',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },

      // DEZEMBRO 2025 - EVENTOS FINAIS
      {
         titulo: 'Expo Tech Brasil Central',
         financiadorTipo: 'publico',
         financiadorNome: 'Governo do Estado de Mato Grosso',
         descricao: 'Maior exposição de tecnologia da região Centro-Oeste.',
         categoriaId: catTecnologia?.id,
         organizadorId: admin.id,
         dataInicio: new Date('2025-12-20T08:00:00'),
         dataFim: new Date('2025-12-20T20:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T20:00:00'),
         capacidadeMaxima: 2000,
         vagasDisponiveis: 2000,
         valorInscricao: 0,
         tipoEvento: 'presencial',
         LocalNome: 'Parque de Exposições Jonas Pinheiro',
         LocalEndereco: 'Av. Beira Rio',
         LocalNumero: 's/n',
         LocalComplemento: '',
         LocalBairro: 'Dom Aquino',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78015-480',
         LocalCapacidade: 1000,
         LocalLatitude: -15.6162,
         LocalLongitude: -56.0998,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo14',
         linkPaginaEvento: 'https://expotechbc.com.br',
         status: 'publicado',
         destaque: true,
         imagemCapa:
            'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
      },
      {
         titulo: 'Curso Avançado de Machine Learning',
         financiadorTipo: 'publico',
         financiadorNome: 'Universidade Federal de Mato Grosso (UFMT)',
         descricao: 'Curso intensivo sobre ML e Deep Learning com certificado.',
         categoriaId: catIA?.id,
         organizadorId: organizador.id,
         dataInicio: new Date('2025-12-10T08:00:00'),
         dataFim: new Date('2025-12-10T18:00:00'),
         horarioAbertura: new Date('1970-01-01T08:00:00'),
         horarioEncerramento: new Date('1970-01-01T18:00:00'),
         capacidadeMaxima: 40,
         vagasDisponiveis: 40,
         valorInscricao: 500.0,
         tipoEvento: 'presencial',
         LocalNome: 'Auditório da UFMT',
         LocalEndereco: 'Av. Fernando Corrêa da Costa',
         LocalNumero: '2367',
         LocalComplemento: 'Universidade Federal de Mato Grosso',
         LocalBairro: 'Boa Esperança',
         LocalCidade: 'Cuiabá',
         LocalEstado: 'MT',
         LocalCep: '78060-900',
         LocalCapacidade: 700,
         LocalLatitude: -15.6080739,
         LocalLongitude: -56.0641917,
         LocalLinkGoogleMaps: 'https://maps.app.goo.gl/exemplo15',
         status: 'publicado',
         destaque: false,
         imagemCapa:
            'https://caltechsites-prod-assets.s3.amazonaws.com/scienceexchange/images/AI-vs-ML_b63MzqT_JUll2of.orig.2e16d0ba.fill-933x525-c100.jpg',
      },
   ]

   for (const evento of eventos) {
      await prisma.evento.create({
         data: evento,
      })
   }

   console.log('✅ Eventos criados')

   console.log('🎉 Seed concluído com sucesso!')
   console.log('📊 Total de eventos criados:', eventos.length)
}

main()
   .catch((e) => {
      console.error('❌ Erro no seed:', e)
      process.exit(1)
   })
   .finally(async () => {
      await prisma.$disconnect()
   })
